WIND_API_FIELD = {
    '短期借款': 'st_borrow',
    '交易性金融负债': 'tradable_fin_liab',
    '应付票据': 'notes_payable',
    '一年内到期的非流动负债': 'non_cur_liab_due_within_1y',
    '长期借款': 'lt_borrow',
    '应付债券': 'bonds_payable',
    '货币资金': 'monetary_cap',
    '交易性金融资产': 'tradable_fin_assets',
    '可供出售金融资产': 'fin_assets_avail_for_sale',
    '持有至到期投资': 'held_to_mty_invest',
    '投资性房地产': 'invest_real_estate',
    '定期存款': 'time_deposits',
    '其他资产': 'oth_assets',
    '长期应收款': 'long_term_rec',
    '非经常性损益': 'extraordinary',
    '财务费用': 'fin_exp_is',
    '利息净收入': 'net_int_inc',
    '利息收入': 'int_inc',
    '所有者权益合计': 'tot_equity',
    '营业收入TTM': 'or_ttm2',
    '营业利润': 'opprofit',
    '净资产收益率TTM': 'roe_ttm2',
    '归属母公司股东的净利润TTM': 'netprofit_ttm2',
    '净利润':'net_profit_is',
    '是否分红': 'div_ifdiv',
    '经营活动产生的现金流量净额': 'net_cash_flows_oper_act',
}